# Generated by Django 4.1.5 on 2023-04-02 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category title')),
                ('slug', models.SlugField(max_length=55, verbose_name='category slug')),
                ('description', models.TextField(blank=True, verbose_name='category description')),
                ('category_image', models.ImageField(blank=True, upload_to='category', verbose_name='category image')),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('is_featured', models.BooleanField(verbose_name='is featured')),
                ('choice', models.CharField(choices=[('home_decore', 'home_decore'), ('dress', 'dress'), ('footwear', 'footwear'), ('jewellery', 'jewellery'), ('crockeries', 'crokeries'), ('cosmetics', 'cosmestics'), ('gadgets', 'gadgets')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=150, verbose_name='Location')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('phono', models.CharField(default='', max_length=15)),
                ('code', models.TextField(default='Pin Code', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product Title')),
                ('slug', models.SlugField(max_length=150, verbose_name='product slug')),
                ('sku', models.CharField(max_length=225, unique='True', verbose_name=' unique product ID (SKU)')),
                ('description', models.TextField(blank='True', null='True', verbose_name='Detail Description')),
                ('product_image', models.ImageField(blank='True', null='True', upload_to='product', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('is_featured', models.BooleanField(verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Relatedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='related')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50, null=True)),
                ('total', models.FloatField(null=True)),
                ('subtotal', models.FloatField(null=True)),
                ('orderd_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date and Time')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('On the way', 'On the way'), ('deliverd', 'delivered')], default='pending', max_length=130)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.customerdetails', verbose_name='shipping addresss')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1', verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
