# Generated by Django 4.1.5 on 2023-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='code',
            field=models.CharField(default='Pin Code', max_length=15),
        ),
    ]
