# Generated by Django 4.1.5 on 2023-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_alter_customerdetails_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Pin Code'),
        ),
    ]
