# Generated by Django 4.1.5 on 2023-04-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_customerdetails_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='category_img',
        ),
    ]
